### PR TITLE
Export mountinfo::MountInfoParser

### PR DESCRIPTION
**Pull request by agrover**
Hi, I'd like to use `MountInfoParser` and was hoping libmount could export it.

### CODE REVIEW

**Comment by tailhook** [comment]
I'm fine with this. However, I should take a closer look to review the public API before a release because we are going to maintain it for long time.

Your feedback is valuable for this thing. Do you find current API good? Does it solves your task?

**Comment by agrover** [comment]
BTW I actually extended another crate that parsed /proc/mount to also handle mountinfo here: https://github.com/stemjail/mnt-rs/pull/4 but which unfortunately hasn't been picked up yet. BTW libmount wouldn't want to take that code because it's under a different license.

Some nice things there that libmount might want to adopt are small helper constructors that handle reading from /proc/self/mountinfo (or /proc/(pid)/mountinfo) without making the caller do this. Going along with that would be the need for the MountInfoParser to own the buffer instead of just having a reference. I started to work on this but wasn't sure how to handle io:Errors that would now be possible. mnt-rs had a From conversion for io:Error to its ParseError type, but libmount's ParseError is a little more specialized so that didn't seem like an obviously good way to go.

**Comment by tailhook** [comment]
> Some nice things there that libmount might want to adopt are small helper constructors

Well, what's your use case? I believe mountinfo is used just for few "system level" things and it's not hard to write two lines `open, read_to_end`. 

> Going along with that would be the need for the MountInfoParser to own the buffer

You can't return reference borrowed from the internal buffer when using Iterator trait. So either get rid of iterator or return fully owned entry.

I don't think it's justified. `read_to_end` is easy and mount table should be too large to have memory constraints. On other hand, quick scanning over list of mountpoints is a common use case I think.

----

For what it worth error type is not a problem, we can turn it into an enum. And it should be public API too. (your PR omits it)

**Comment by agrover** [comment]
OK, I was just comparing to what the other crate did, I'm fine with current impl, tbh.

BTW for how I'd like to use MountInfoParser, I have a prelim commit with the changes for our project: https://github.com/agrover/stratisd/commit/cc294f803c021c6bc62b8b7933243c0adf99ac48. (We also probably could be using libmount for mounting and unmounting since we need that too, but this commit doesn't yet.)

**Comment by agrover** [comment]
Updated PR to export ParseError as well.

**Comment by tailhook** [comment]
Okay, further investigation shows:

1. `MountPoint`  type should be exported (it's a result of an iteration)
2. What do you think of just publishing a mountinfo module? This way `Parser`, `ParseError` and `MountPoint` would be conveniently exported together. And also it's clear that `MountPoint` does nothing for other libmount operations and just an entry in mountinfo file.

**Comment by agrover** [comment]
Both points makes sense and sound good to me.

**Comment by tailhook** [comment]
Okay. Done in the current master.

**Comment by agrover** [comment]
Great, thanks so much! I look forward to making use of this! btw please also update the checkbox on the main README feature list since mountinfo parsing is now supported :smiley: :smiley: :smiley:

**Comment by tailhook** [comment]
Released as v0.1.9 with no further changes (apart from docstrings).

**Pull request closed without merging**
